name: CI pipeline

run-name: ${{ github.actor }} is running the CI pipeline

on: [push]

jobs:
  Static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.2
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install requirements
        run: make install
      - name: Run Mypy
        run: mypy .
      - name: Run unit tests
        run: make unit_tests
